
unittest:
  stage: test
  image: python:3.7
  script:
    - pip3 install -r requirements.txt --extra-index-url "https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@${NEXUS_HOST}/repository/pypi-hosted/simple/"
    - pip3 install .
    - python3 -m flake8
    - python3 -m pytest -W ignore tests/unittests -vv

e2e-test:
  stage: test
  # image: docker:latest
  # services:
  #   - docker:dind
  # before_script:
  #   - apk add bash curl
  #   - curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
  #   - chmod +x /usr/bin/docker-compose
  image: jonaskello/docker-and-compose:1.12.1-1.8.0
  services:
    - docker:1.12.1-dind
  script:
    - ./run_tests.sh -d -e

deploy-docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --build-arg NEXUS_HOST=${NEXUS_HOST} --build-arg NEXUS_USERNAME=${NEXUS_USERNAME} --build-arg NEXUS_PASSWORD=${NEXUS_PASSWORD}  --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}"
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}" "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_latest"
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_latest"
  except:
    - tags

deploy-docker-tags:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --build-arg NEXUS_HOST=${NEXUS_HOST} --build-arg NEXUS_USERNAME=${NEXUS_USERNAME} --build-arg NEXUS_PASSWORD=${NEXUS_PASSWORD} --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - tags
  except:
    - /^public_.*$/
