
# build-deploy-pypi:
#   stage: build
#   variables:
#     PIP_REPO_DOMAIN: nexus.changedynamix.io
#     PIP_REPO_PATH: repository/pypi-hosted/
#     PIP_REPO_URL: https://${PIP_REPO_DOMAIN}/${PIP_REPO_PATH}

#     PIP_TRUSTED_HOST: ${PIP_REPO_DOMAIN}
#     PIP_EXTRA_INDEX_URL: https://${PIP_REPO_DOMAIN}/${PIP_REPO_PATH}/simple
#   script:
#     - python3 setup.py bdist_wheel # install for distribution
#     - twine upload --repository-url "$PIP_REPO_URL" -u "$NEXUS_USERNAME" -p "$NEXUS_PASSWORD" dist/*
#   except:
#     - /^public_.*$/
#     - /^qa_.*$/
#     - /^stage_.*$/
#     - /^prod_.*$/

deploy-docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}"
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}" "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_latest"
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_latest"
  except:
    - tags

deploy-docker-tags:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - tags
  except:
    - /^public_.*$/
