version: '3.7'
services:
  redis:
    image: redis:5.0
    ports:
      - 6100:6379
  jwt:
    image: registry.gitlab.com/techlock/mock-jwt-service:master_3842a8a6ed4f290d5720a5ec754a23eea67cbdae
    environment:
      FLASK_JWT_IDENTITY_CLAIM: sub
      FLASK_JWT_USER_CLAIMS: claims
    ports:
      - 6101:5000
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 6102:8000
  cognito:
    image: motoserver/moto
    ports:
      - 6103:5000
    command: -p 5000 cognito-idp

  init:
    build:
      context: .
      args:
        NEXUS_HOST: ${NEXUS_HOST}
        NEXUS_USERNAME: ${NEXUS_USERNAME}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
    depends_on:
      - redis
      - dynamodb
      - cognito
      - jwt
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_SOCKET_CONNECT_TIMEOUT: 30
      REDIS_IS_CLUSTER: 'false'
      REDIS_SKIP_FULL_COVERAGE_CHECK: 'false'
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
      COGNITO_IDP_ENDPOINT_URL: http://cognito:5000
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: us-east-1
      STAGE: test
      # LOG_LEVEL: debug
      TENANT_ID: test
      NO_CACHE: ${NO_CACHE:-true}
      FLASK_JWT_ALGORITHM: RS256
      JWKS_URLS: 'http://jwt:5000/.well-known/jwks.json'
    ports:
      - 5000
    entrypoint:
      - "/usr/bin/wait-for-it"
      - "cognito:5000"
      - "-s"
      - "--timeout=30"
      - "--"
      - 'python'
      - '/app/tests/e2e_tests/conftest.py'

  api:
    build:
      context: .
      args:
        NEXUS_HOST: ${NEXUS_HOST}
        NEXUS_USERNAME: ${NEXUS_USERNAME}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
    depends_on:
      - redis
      - dynamodb
      - cognito
      - jwt
      - init
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_SOCKET_CONNECT_TIMEOUT: 30
      REDIS_IS_CLUSTER: 'false'
      REDIS_SKIP_FULL_COVERAGE_CHECK: 'false'
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
      COGNITO_IDP_ENDPOINT_URL: http://cognito:5000
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: us-east-1
      STAGE: test
      # LOG_LEVEL: debug
      TENANT_ID: test
      NO_CACHE: ${NO_CACHE:-true}
      FLASK_JWT_ALGORITHM: RS256
      JWKS_URLS: 'http://jwt:5000/.well-known/jwks.json'
    ports:
      - 6105:5000
