"""empty message

Revision ID: 63c703c874c5
Revises: 80336b9bf2ac
Create Date: 2020-07-14 13:30:57.007007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c703c874c5'
down_revision = '80336b9bf2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ftp_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ftp_username')
    # ### end Alembic commands ###
